language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
gemfile:
  - ci/Gemfile-rails-3-0
  - ci/Gemfile-rails-3-1
  - ci/Gemfile-rails-3-2
  - ci/Gemfile-rails-4-0
matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: ci/Gemfile-rails-4-0
