rvm:
  - 1.8.7
  - 1.9.3
gemfile:
  - ci/Gemfile.rails-2.3.x
  - ci/Gemfile.rails-3.0.x
  - ci/Gemfile.rails-3.1.x
env:
  - DB=sqlite
  - DB=mysql
before_script:
  - "mysql -e 'create database myapp_test;' >/dev/null"